//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emBrokerExport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AndelerCorpEntities : DbContext
    {
        public AndelerCorpEntities()
            : base("name=AndelerCorpEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Database.CommandTimeout = 400;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Create_emPower_emBroker_Accounts> Create_emPower_emBroker_Accounts { get; set; }
        public virtual DbSet<Create_empower_embroker_Invoice_InvoiceLineitems> Create_empower_embroker_Invoice_InvoiceLineitems { get; set; }
        public virtual DbSet<Create_empower_embroker_Payment_By_AccountNumber> Create_empower_embroker_Payment_By_AccountNumber { get; set; }
        public virtual DbSet<Create_emPower_emBroker_Sitecodes_By_AccountKey> Create_emPower_emBroker_Sitecodes_By_AccountKey { get; set; }
        public virtual DbSet<Create_emPower_emBroker_Invoices> Create_emPower_emBroker_Invoices { get; set; }
    }
}
