//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emBrokerExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_emPower_emBroker_Sitecodes_By_AccountKey
    {
        public System.Guid ClientId { get; set; }
        public string Sitecodevalue { get; set; }
        public string ReferenceSitecodeId { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public System.DateTime SitecodeStartDate { get; set; }
        public Nullable<System.DateTime> SitecodeEndDate { get; set; }
        public System.Guid AccountKey { get; set; }
        public string Status { get; set; }
    }
}
