//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emBrokerExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_emPower_emBroker_Accounts
    {
        public System.Guid ClientId { get; set; }
        public string AcccountName { get; set; }
        public System.Guid AccountKey { get; set; }
        public string email { get; set; }
        public string Mobile { get; set; }
        public int ReferenceAccountId { get; set; }
        public System.DateTime AccountStartDate { get; set; }
        public string Status { get; set; }
    }
}
