//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emBrokerExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_empower_embroker_Payment_By_AccountNumber
    {
        public Nullable<decimal> AccountDeposit { get; set; }
        public string Currency { get; set; }
        public string Description { get; set; }
        public string ActionType { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string ReferencePaymentId { get; set; }
        public int ReferenceAccountId { get; set; }
        public int ReferenceInvoiceId { get; set; }
    }
}
