//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emBrokerExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_empower_embroker_Invoice_InvoiceLineitems
    {
        public decimal InvoiceUnits { get; set; }
        public string ReferenceSitecode { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public System.DateTime ServiceStartDate { get; set; }
        public Nullable<System.DateTime> ServiceEndDate { get; set; }
        public System.DateTime UsageStartDate { get; set; }
        public System.DateTime UsageEndDate { get; set; }
        public decimal UsageCharge { get; set; }
        public System.Guid InvoiceKey { get; set; }
        public System.Guid AccountKey { get; set; }
    }
}
