//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emBrokerExport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Create_emPower_emBroker_Invoices
    {
        public System.Guid ClientId { get; set; }
        public int ReferenceAccountNumber { get; set; }
        public int ReferenceInvoiceId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> TotalInvoiceAmount { get; set; }
        public System.Guid InvoiceKey { get; set; }
        public Nullable<bool> Incorrect { get; set; }
        public System.Guid AccountKey { get; set; }
        public Nullable<System.DateTime> PaidInFullDate { get; set; }
        public string Currency { get; set; }
        public string Status { get; set; }
    }
}
